redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\KS Viswa\\Documents\\vita-insuratech\\frontend"
publishOrigin = "config"
commandOrigin = "config"
base = "C:\\Users\\KS Viswa\\Documents\\vita-insuratech\\frontend"
command = "echo 'Static site - no build needed'"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/api/*"
to = "https://vita-insuratech-api.netlify.app/api/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/workers_dashboard.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]