# Generated by Django 6.0.3 on 2026-04-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=10)),
                ('arce_score', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('movement', models.IntegerField()),
                ('activity', models.IntegerField()),
                ('location_valid', models.IntegerField()),
                ('rain', models.FloatField()),
                ('temp', models.FloatField()),
                ('aqi', models.FloatField()),
                ('zone', models.CharField(max_length=10)),
                ('social_signal', models.JSONField()),
                ('svm_anomaly', models.IntegerField()),
                ('cluster_flag', models.IntegerField()),
                ('decision', models.CharField(max_length=10)),
                ('arce_score', models.FloatField()),
                ('risk_level', models.CharField(max_length=10)),
                ('claims_in_zone', models.IntegerField()),
                ('reported_outcome', models.CharField(blank=True, max_length=20, null=True)),
                ('label', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
